### PR TITLE
Added some basic abc info

### PR DESCRIPTION
**Pull request by weitzhandler**
I wasn't sure on the projects, but it would be appropriate to explain what each of the 5 NuGet packages does.

### CODE REVIEW

**Comment by weitzhandler** [comment]
>TF400813: The user '7349179d-b6a9-4e56-ba0e-b060d0ca0219' is not authorized to access this resource.

@jeromelaban what does that mean?

**Comment by jeromelaban** [comment]
It's an azure devops issue, I'll fix it so your PR passes.

**Comment by jeromelaban** [comment]
Apologies for the open/close, restarting PR builds is not particularly efficient, we'll have to find something.

**Comment by weitzhandler** [comment]
You are awesome. Thank you!

**Pull request merged**
